apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dotnet-app-gitops
spec:
  destination:
    namespace: dev
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: gitops
    repoURL: 'https://github.com/osa-ora/simple_dotnet'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
