name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --logger trx --verbosity normal
    - name: CURL-ACTION
      # You may pin to the exact commit or the version.
      # uses: enflo/curl-action@fabe347922c7a9e88bafa15c4b7d6326ea802695
      uses: enflo/curl-action@v1.2
      with:
      # curl arguments
        curl: -k -X POST https://api.cluster-66a1.66a1.sandbox1049.opentlc.com:6443/apis/build.openshift.io/v1/namespaces/dev/buildconfigs/simple-dotnet-git/webhooks/9dfa4520e81ce0e7/generic
          
